#!/usr/bin/env bash
# =============================================================================
# DigilistSaaS Local Test Environment Setup
# =============================================================================
#
# Sets up the local environment for running tests deterministically.
# Run once after cloning or when environment breaks.
#
# Usage: ./scripts/setup-local.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_header() {
    echo ""
    echo -e "${BLUE}================================================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}================================================================${NC}"
    echo ""
}

print_success() { echo -e "${GREEN}✓ $1${NC}"; }
print_error() { echo -e "${RED}✗ $1${NC}"; }
print_warning() { echo -e "${YELLOW}⚠ $1${NC}"; }

# =============================================================================
# Step 1: Check prerequisites
# =============================================================================
print_header "Checking Prerequisites"

if ! command -v node &> /dev/null; then
    print_error "Node.js not found. Install Node.js 20+"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    print_error "Node.js 20+ required, found v$NODE_VERSION"
    exit 1
fi
print_success "Node.js v$NODE_VERSION detected"

if ! command -v npx &> /dev/null; then
    print_error "npx not found. Install Node.js 20+"
    exit 1
fi
print_success "npx available"

# =============================================================================
# Step 2: Install dependencies
# =============================================================================
print_header "Installing Dependencies"

cd "$ROOT_DIR"
npm install
print_success "npm install complete"

# =============================================================================
# Step 3: Create .env.test file
# =============================================================================
print_header "Creating .env.test"

# Convex URL from convex.json or environment
CONVEX_URL="${VITE_CONVEX_URL:-}"

if [ -z "$CONVEX_URL" ] && [ -f "$ROOT_DIR/convex.json" ]; then
    # Try to extract from convex.json
    CONVEX_URL=$(node -e "const c = require('./convex.json'); console.log(c.prodUrl || c.url || '')" 2>/dev/null || echo "")
fi

cat > "$ROOT_DIR/.env.test" << EOF
# =============================================================================
# DigilistSaaS Test Environment Variables
# Generated by scripts/setup-local.sh on $(date)
# =============================================================================

# Convex
VITE_CONVEX_URL=${CONVEX_URL:-https://your-project.convex.cloud}

# Test Config
E2E_TENANT_ID=
E2E_USER_ID=
E2E_TOKEN=
EOF

print_success "Created .env.test"

# =============================================================================
# Step 4: Seed test data via Convex
# =============================================================================
print_header "Seeding Test Data"

npx convex run seeds:seedAll || print_warning "Seed script failed - Convex dev server may not be running"

# =============================================================================
# Step 5: Verify setup
# =============================================================================
print_header "Verifying Setup"

# Check if Convex dev server is accessible
if npx convex status &> /dev/null; then
    print_success "Convex accessible"
else
    print_warning "Convex dev server may not be running. Start with: npx convex dev"
fi

# =============================================================================
# Summary
# =============================================================================
print_header "Setup Complete"

echo "Environment variables are in: .env.test"
echo ""
echo "To run tests:"
echo "  source .env.test"
echo "  ./scripts/test.sh all"
echo ""
echo "To start the dev server:"
echo "  npx convex dev"
echo ""
